// Generated by https://quicktype.io

export interface Network {
  network: NetworkClass;
}

export interface NetworkClass {
  company:  string[];
  href:     string;
  id:       string;
  location: Location;
  name:     string;
  stations: Station[];
}

export interface Location {
  city:      string;
  country:   string;
  latitude:  number;
  longitude: number;
}

export interface Station {
  empty_slots: number;
  extra:       Extra;
  free_bikes:  number;
  id:          string;
  latitude:    number;
  longitude:   number;
  name:        string;
  timestamp:   string;
}

export interface Extra {
  id:      string;
  id_expl: string;
}
